In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
# Sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good']

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
# Define the Vocabulary Size 
voc_size=10000

In [6]:
# One Hot Representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[6441, 4551, 3516, 8450],
 [6441, 4551, 3516, 1169],
 [6441, 3825, 3516, 3807],
 [333, 9193, 8591, 1935, 8420],
 [333, 9193, 8591, 1935, 6924],
 [2065, 6441, 2725, 3516, 5274],
 [2856, 6619, 7992, 1935]]

In [7]:
# Word Embedding Representation 

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6441 4551 3516 8450]
 [   0    0    0    0 6441 4551 3516 1169]
 [   0    0    0    0 6441 3825 3516 3807]
 [   0    0    0  333 9193 8591 1935 8420]
 [   0    0    0  333 9193 8591 1935 6924]
 [   0    0    0 2065 6441 2725 3516 5274]
 [   0    0    0    0 2856 6619 7992 1935]]


In [13]:
# feature Representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile(optimizer='adam',loss='mse')

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 219ms/step


array([[[-0.02699815, -0.00494405, -0.02131811, -0.04263526,
          0.00758363, -0.01571054,  0.00415598,  0.01233722,
         -0.02732645, -0.04121267],
        [-0.02699815, -0.00494405, -0.02131811, -0.04263526,
          0.00758363, -0.01571054,  0.00415598,  0.01233722,
         -0.02732645, -0.04121267],
        [-0.02699815, -0.00494405, -0.02131811, -0.04263526,
          0.00758363, -0.01571054,  0.00415598,  0.01233722,
         -0.02732645, -0.04121267],
        [-0.02699815, -0.00494405, -0.02131811, -0.04263526,
          0.00758363, -0.01571054,  0.00415598,  0.01233722,
         -0.02732645, -0.04121267],
        [-0.04699947, -0.00115005,  0.00057062, -0.02672731,
         -0.03246558, -0.03498551,  0.01123574, -0.00318366,
          0.02033893,  0.04170385],
        [ 0.01718782,  0.03024281,  0.02108296, -0.02580669,
         -0.04246989,  0.00451465, -0.01180435, -0.0473564 ,
         -0.00902877,  0.04991101],
        [ 0.00381774, -0.03639434, -0.02171698,  0.0

In [18]:
model.predict(embedded_docs[0]) ## Dimension representation of each word of first sentence

1/1 [==============================] - 0s 25ms/step


array([[-0.02699815, -0.00494405, -0.02131811, -0.04263526,  0.00758363,
        -0.01571054,  0.00415598,  0.01233722, -0.02732645, -0.04121267],
       [-0.02699815, -0.00494405, -0.02131811, -0.04263526,  0.00758363,
        -0.01571054,  0.00415598,  0.01233722, -0.02732645, -0.04121267],
       [-0.02699815, -0.00494405, -0.02131811, -0.04263526,  0.00758363,
        -0.01571054,  0.00415598,  0.01233722, -0.02732645, -0.04121267],
       [-0.02699815, -0.00494405, -0.02131811, -0.04263526,  0.00758363,
        -0.01571054,  0.00415598,  0.01233722, -0.02732645, -0.04121267],
       [-0.04699947, -0.00115005,  0.00057062, -0.02672731, -0.03246558,
        -0.03498551,  0.01123574, -0.00318366,  0.02033893,  0.04170385],
       [ 0.01718782,  0.03024281,  0.02108296, -0.02580669, -0.04246989,
         0.00451465, -0.01180435, -0.0473564 , -0.00902877,  0.04991101],
       [ 0.00381774, -0.03639434, -0.02171698,  0.02272545, -0.0291658 ,
         0.03854673, -0.04005479,  0.03875503